### ISSUE TITLE
menus are incorrect

### ISSUE THREAD

**Issue by doom99** [cathelijne/straightline#3]
Hello - the below is used for menus:

`<li><a href="{{ item.path is defined ? item.path : item.link }}">{{ item.label }}</a></li>`

that is (I think) incorrect.  You can see this by clicking one of your menu links and then clicking the menu link again - it seems to add an extra "page/" or similar.  to the url.   I believe what you really want is 

`<li><a href="{{ item.link is defined ? item.link : homepage }}">{{ item.label }}</a></li>`

(this also looks cleaner as you get the page "name" rather than a page #)  I've used homepage as the error condition but I suppose you could send to a 404 or something elese.

**Comment by nestordedios** [comment]
This issue is fixed in this commit 0082acb07dba654120d52c6a529e04ae1079c2e1

**Comment by cathelijne** [comment]
Thanks for fixing @nestordedios

**Comment by nestordedios** [comment]
You are welcome @cathelijne
